name: Random Auto Commit
on:
  schedule:
    - cron: '30 4 * * *'   # 10:00 AM IST
    - cron: '30 5 * * *'   # 11:00 AM IST
    - cron: '30 6 * * *'   # 12:00 PM IST
    - cron: '30 7 * * *'   # 01:00 PM IST
    - cron: '30 8 * * *'   # 02:00 PM IST
    - cron: '30 9 * * *'   # 03:00 PM IST
    - cron: '30 10 * * *'  # 04:00 PM IST
    - cron: '30 11 * * *'  # 05:00 PM IST
    - cron: '30 12 * * *'  # 06:00 PM IST
    - cron: '30 13 * * *'  # 07:00 PM IST
    - cron: '30 14 * * *'  # 08:00 PM IST
    - cron: '30 15 * * *'  # 09:00 PM IST
    - cron: '30 16 * * *'  # 10:00 PM IST
    - cron: '30 17 * * *'  # 11:00 PM IST
  workflow_dispatch:
permissions:
  contents: write
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Random commit
        run: |
          RANDOM_NUM=$((RANDOM % 100))
          if [ $RANDOM_NUM -lt 70 ]; then
            echo "$(date)" >> activity.txt
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add .
            git commit -m "update $(date)" || exit 0
            git push
          else
            echo "Skipping commit"
          fi
